import type { Metadata } from 'next';
import './globals.css';
import Channels from '@/components/sections/section.leftSideChannels/section.leftsideChannels';
import Friends from '@/components/sections/section.friends/section.friends';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased font-sans`}>
        <div className="flex flex-row w-full h-screen">
          <Channels />
          <Friends />
          {children}
        </div>
      </body>
    </html>
  );
}
